### ISSUE TITLE
Performance decrease

### ISSUE THREAD

**Issue by legosteenjaap** [ImUrX/LittleTweaks#4]
Weird consistent spikes

**Comment by ImUrX** [comment]
Where do the spikes appear? When there is an automatic device change? It's something that happens in most games but in this case happens because of OpenAL states changing in main thread

**Comment by legosteenjaap** [comment]
Just a constant fps decrease

**Comment by ImUrX** [comment]
I fixed a bug I just noticed, update the mod and check it out :p

**Comment by ImUrX** [comment]
Gonna close this because there is no more input from the user
