### ISSUE TITLE
Compost Addition?

### ISSUE THREAD

**Issue by Zethin64** [ImUrX/LittleTweaks#5]
Hello! Love the mod, always closing the game to fix sound.

Is there any chance you would add extra items to be compostable, i.e. Cooked Meats? I've always wished I could turn my massive pile of cooked chickens into BoneMeal.

Regardles - thank you for the mod!

**Comment by ImUrX** [comment]
Sorry this mod doesnt modify anything related to server-side, its strictly a client-side mod :c
