### ISSUE TITLE
Recommendation - Add C418 Volume Alpha / Beta Music

### ISSUE THREAD

**Issue by MayorBryce** [ImUrX/LittleTweaks#8]
In Minecraft Volume Alpha & Beta, a number of songs have extensions, and some songs go completely unused. If you can make it so these songs are present during the game, then that would be great! If you need to download these, I’d reccomend KHInsider, just google Minecraft OST Download and select KHInsider. Completely safe site, I’ve downloaded thousands of songs from it. However, I don’t know how to add them. Thank you!

**Comment by ImUrX** [comment]
Sorry but I dont have a license to distribute C418's music, maybe if there was a more indirect way of adding them. You could just make a resource pack too
